# Generated by Django 3.2.8 on 2021-10-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Cliente')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Cliente')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome Serviço')),
                ('descript', models.CharField(max_length=300, verbose_name='Descrição do Serviço')),
                ('icon', models.CharField(max_length=50, verbose_name='Icone')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Membro')),
                ('degree', models.CharField(max_length=200, verbose_name='Habilitação')),
                ('thumb', models.CharField(max_length=50, verbose_name='Foto')),
            ],
        ),
    ]
